import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

//component
import Header from "@/components/Header";
import PageTansition from "@/components/PageTansition";
import StairTransition from "@/components/StairTransition";

const JetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  Weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono",
});

export const metadata = {
  title: "Faniry-Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={JetBrainsMono.variable}>
        <Header />
        <StairTransition/>
        <PageTansition>
          {children}
        </PageTansition>

      </body>
    </html>
  );
}
